In [4]:
import numpy as np
from numpy import dot
import math
from scipy import linalg

In [40]:
def SVD(A):
    
    AT = A.transpose()
    ATA = AT.dot(A)
    
    M = {}
    M['S'], M['V'] = np.linalg.eig(ATA)
    print(np.linalg.eig(ATA))
    
    for i in range(len(M['S'])):
        M['S'][i] = math.sqrt(abs(M['S'][i]))
    #M['S'] = sorted(M['S'], reverse=1)
    M['S'] = np.diag(M['S'])
    
    M['U'] = A.dot(M['V']).dot(np.linalg.inv(M['S']))
    M['USVT'] = M['U'].dot(M['S'].dot(M['V'].transpose()))
    
    return M


In [42]:
A = np.array([[0, 1, 1], [math.sqrt(2), 2, 0], [0, 1, 1]])
matrix = SVD(A)

print("--- OLD ---")
print(A)

print("\n--- NEW ---")
print(np.around(matrix['USVT'], decimals=3))

print("\n--- U ---")
print(np.around(matrix['U'], decimals=3))

print("\n--- S ---")
print(np.around(matrix['S'], decimals=3))

print("--- V ---")
print(np.around(matrix['V'], decimals=3))

(array([ 8.00000000e+00, -7.68216532e-18,  2.00000000e+00]), array([[-4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [-8.66025404e-01, -5.00000000e-01, -7.84321844e-17],
       [-2.88675135e-01,  5.00000000e-01,  8.16496581e-01]]))
--- OLD ---
[[0.         1.         1.        ]
 [1.41421356 2.         0.        ]
 [0.         1.         1.        ]]

--- NEW ---
[[0.    1.    1.   ]
 [1.414 2.    0.   ]
 [0.    1.    1.   ]]

--- U ---
[[-0.408  0.     0.577]
 [-0.816  0.    -0.577]
 [-0.408  0.     0.577]]

--- S ---
[[2.828 0.    0.   ]
 [0.    0.    0.   ]
 [0.    0.    1.414]]
--- V ---
[[-0.408  0.707 -0.577]
 [-0.866 -0.5   -0.   ]
 [-0.289  0.5    0.816]]
